/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Class.DtbsHelper;
import Class.LogInGraphic;
import Class.MysqlConnect;
import java.awt.Color;
import java.awt.Cursor;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yunus
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    String imagePth = null;

    public AdminHome() {
        initComponents();
        setLocationRelativeTo(null);
        tbl_Address.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbl_Address.getColumnModel().getColumn(1).setPreferredWidth(600);
        tbl_Address.getColumnModel().getColumn(2).setPreferredWidth(70);
        tbl_feedbacks.getColumnModel().getColumn(0).setPreferredWidth(25);
        tbl_feedbacks.getColumnModel().getColumn(1).setPreferredWidth(500);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnl_home = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rbtn_black = new javax.swing.JRadioButton();
        lbl_usernameUp = new javax.swing.JLabel();
        lbl_picture = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        lbl_welcome = new javax.swing.JLabel();
        lbl_imageUp = new javax.swing.JLabel();
        lbl_b4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_get = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Address = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        lbl_b5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btn_register = new javax.swing.JButton();
        btn_image = new javax.swing.JButton();
        lbl_image = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbtn_male = new javax.swing.JRadioButton();
        rbtn_female = new javax.swing.JRadioButton();
        lbl_NewPassword = new javax.swing.JLabel();
        txt_NPassword = new javax.swing.JTextField();
        lbl_b6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_feedbacks = new javax.swing.JTable();
        lbl_b7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnl_home.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        rbtn_black.setText("Black Theme");
        rbtn_black.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtn_black.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_blackActionPerformed(evt);
            }
        });

        lbl_usernameUp.setBackground(new java.awt.Color(255, 255, 255));
        lbl_usernameUp.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lbl_usernameUp.setForeground(new java.awt.Color(0, 0, 0));
        lbl_usernameUp.setText("Username:");

        lbl_picture.setBackground(new java.awt.Color(255, 255, 255));
        lbl_picture.setForeground(new java.awt.Color(255, 255, 255));
        lbl_picture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/home.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADDRESS TRACKiNG SYSTEM(Admın)");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("--");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 720, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_picture, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rbtn_black, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_usernameUp, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_usernameUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(rbtn_black)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(lbl_picture, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_home.add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 120);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel4.setLayout(null);

        lbl_welcome.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        lbl_welcome.setForeground(new java.awt.Color(0, 0, 0));
        lbl_welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_welcome.setText("WELCOME BACK");
        jPanel4.add(lbl_welcome);
        lbl_welcome.setBounds(38, 341, 697, 68);

        lbl_imageUp.setBackground(new java.awt.Color(255, 255, 255));
        lbl_imageUp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_imageUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_imageUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/FSMVU-EN-5 (1).png"))); // NOI18N
        lbl_imageUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_imageUpMouseClicked(evt);
            }
        });
        jPanel4.add(lbl_imageUp);
        lbl_imageUp.setBounds(276, 73, 250, 250);

        lbl_b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İcon/backgroundHome.jpg"))); // NOI18N
        jPanel4.add(lbl_b4);
        lbl_b4.setBounds(1, 1, 790, 440);

        jTabbedPane1.addTab("Home", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 255, 153));
        jPanel5.setLayout(null);

        btn_get.setBackground(new java.awt.Color(0, 0, 0));
        btn_get.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btn_get.setForeground(new java.awt.Color(255, 255, 255));
        btn_get.setText("Get");
        btn_get.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getActionPerformed(evt);
            }
        });
        jPanel5.add(btn_get);
        btn_get.setBounds(230, 10, 110, 30);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportBorder(new javax.swing.border.MatteBorder(null));

        tbl_Address.setBackground(new java.awt.Color(255, 255, 255));
        tbl_Address.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        tbl_Address.setForeground(new java.awt.Color(0, 0, 0));
        tbl_Address.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Adress", "Group"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_Address.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_Address.setRowHeight(70);
        tbl_Address.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tbl_Address.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tbl_Address);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(6, 48, 778, 388);

        btn_delete.setBackground(new java.awt.Color(0, 0, 0));
        btn_delete.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel5.add(btn_delete);
        btn_delete.setBounds(375, 7, 110, 34);

        lbl_b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İcon/backgroundHome.jpg"))); // NOI18N
        jPanel5.add(lbl_b5);
        lbl_b5.setBounds(1, 1, 790, 440);

        jTabbedPane1.addTab("Addresses", jPanel5);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setLayout(null);

        btn_register.setBackground(new java.awt.Color(255, 255, 153));
        btn_register.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btn_register.setForeground(new java.awt.Color(0, 0, 0));
        btn_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/save.png"))); // NOI18N
        btn_register.setText("Save");
        btn_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        jPanel6.add(btn_register);
        btn_register.setBounds(457, 358, 138, 41);

        btn_image.setBackground(new java.awt.Color(255, 255, 153));
        btn_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/photo.png"))); // NOI18N
        btn_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imageActionPerformed(evt);
            }
        });
        jPanel6.add(btn_image);
        btn_image.setBounds(493, 126, 40, 30);

        lbl_image.setIcon(new javax.swing.ImageIcon("C:\\Users\\yunus\\Desktop\\First Year\\SecondTerm\\Bilgisayar Programlama II\\Homework\\Term Project\\iconfinder_user_male2_172626.png")); // NOI18N
        jPanel6.add(lbl_image);
        lbl_image.setBounds(337, 16, 150, 140);
        jPanel6.add(txt_phone);
        txt_phone.setBounds(337, 167, 196, 30);

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel6.add(txt_email);
        txt_email.setBounds(337, 207, 196, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Phone:");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(219, 162, 100, 40);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("E-mail:");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(219, 202, 100, 40);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Gender:");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(219, 306, 100, 40);

        buttonGroup1.add(rbtn_male);
        rbtn_male.setText("Male");
        jPanel6.add(rbtn_male);
        rbtn_male.setBounds(359, 316, 98, 20);

        buttonGroup1.add(rbtn_female);
        rbtn_female.setText("Female");
        jPanel6.add(rbtn_female);
        rbtn_female.setBounds(463, 316, 98, 20);

        lbl_NewPassword.setBackground(new java.awt.Color(255, 255, 255));
        lbl_NewPassword.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lbl_NewPassword.setForeground(new java.awt.Color(0, 0, 0));
        lbl_NewPassword.setText("Password:");
        jPanel6.add(lbl_NewPassword);
        lbl_NewPassword.setBounds(219, 248, 100, 40);
        jPanel6.add(txt_NPassword);
        txt_NPassword.setBounds(337, 253, 192, 30);

        lbl_b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İcon/backgroundHome.jpg"))); // NOI18N
        jPanel6.add(lbl_b6);
        lbl_b6.setBounds(1, 1, 790, 440);

        jTabbedPane1.addTab("Info", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(null);

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/paper-plane.png"))); // NOI18N
        jButton1.setText("get");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);
        jButton1.setBounds(300, 20, 143, 32);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jScrollPane4.setViewportBorder(new javax.swing.border.MatteBorder(null));

        tbl_feedbacks.setBackground(new java.awt.Color(255, 255, 255));
        tbl_feedbacks.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        tbl_feedbacks.setForeground(new java.awt.Color(0, 0, 0));
        tbl_feedbacks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Feedback"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_feedbacks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_feedbacks.setRowHeight(70);
        tbl_feedbacks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(tbl_feedbacks);

        jPanel7.add(jScrollPane4);
        jScrollPane4.setBounds(10, 70, 770, 360);

        lbl_b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İcon/backgroundHome.jpg"))); // NOI18N
        jPanel7.add(lbl_b7);
        lbl_b7.setBounds(1, 1, 790, 440);

        jTabbedPane1.addTab("Feedbacks", jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pnl_home.add(jPanel3);
        jPanel3.setBounds(0, 120, 800, 480);

        getContentPane().add(pnl_home);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void btn_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imageActionPerformed
        JFileChooser filec = new JFileChooser();
        filec.setCurrentDirectory(new File(System.getProperty("user.home")));
        //file extension
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("*.Images", "jpg", "png", "gif");
        filec.addChoosableFileFilter(fileFilter);
        int fileState = filec.showSaveDialog(null);
        if (fileState == JFileChooser.APPROVE_OPTION) {
            File selectedFile = filec.getSelectedFile();
            imagePth = selectedFile.getAbsolutePath();
            // imagePth = path;
            //show the image in the Jlabel
            lbl_image.setIcon(DtbsHelper.rezisePic(imagePth, null, lbl_image));
        }//if the user click cancel
        else if (fileState == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "No image selected");
        }
        {
        }
    }//GEN-LAST:event_btn_imageActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed

        if (!txt_phone.getText().isEmpty()) {
            String query = "UPDATE `admın`  SET phone='" + txt_phone.getText() + "' where username='" + lbl_usernameUp.getText() + "'";
            DtbsHelper.edıtInfo(1, query);
        }
        if (imagePth != null) {
            try {
                InputStream img = new FileInputStream(new File(imagePth));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            String query = "UPDATE `admın`  SET pic='" + imagePth + "' where username='" + lbl_usernameUp.getText() + "'";
            DtbsHelper.edıtInfo(2, query);
            lbl_picture.setIcon(DtbsHelper.rezisePic(imagePth, null, lbl_picture));
        }
        if (!txt_email.getText().isEmpty()) {
            String query = "UPDATE `admın`  SET email='" + txt_email.getText() + "' where username='" + lbl_usernameUp.getText() + "'";
            DtbsHelper.edıtInfo(3, query);
        }
        if (!txt_NPassword.getText().isEmpty()) {
            String query = "UPDATE `admın`  SET pass='" + txt_NPassword.getText() + "' where username='" + lbl_usernameUp.getText() + "'";
            DtbsHelper.edıtInfo(4, query);
        }
        if (rbtn_male.isSelected() || rbtn_female.isSelected()) {
            String gender;
            if (rbtn_male.isSelected()) {
                gender = rbtn_male.getText();
            } else {
                gender = rbtn_female.getText();
            }
            String query = "UPDATE `admın`  SET gender='" + gender + "' where username='" + lbl_usernameUp.getText() + "'";
            DtbsHelper.edıtInfo(5, query);
        }

    }//GEN-LAST:event_btn_registerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl_feedbacks.getModel();
        Connection con = MysqlConnect.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        try {
            ps = con.prepareStatement("SELECT `user`,`feedback` FROM `feedback`");
            rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2)});
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Something went Wrong");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_getActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl_Address.getModel();
        Connection con = MysqlConnect.getConnection();
        PreparedStatement ps;
        ArrayList<String> user = new ArrayList<>();
        ResultSet rs;
        try {
            ps = con.prepareStatement("SELECT `username` FROM `address`");
            rs = ps.executeQuery();
            while (rs.next()) {
                user.add(rs.getString(1));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Something went Wrong");
        }
        for (String users : user) {
            new DtbsHelper().getTable((DefaultTableModel) model, users, 1);
        }
    }//GEN-LAST:event_btn_getActionPerformed

    private void lbl_imageUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_imageUpMouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Do you want to exit", "EXİT", dialogButton);
        if (dialogResult == 0) {
            LogInGraphic logInGraphic = new LogInGraphic();
            logInGraphic.setLocationRelativeTo(null);
            logInGraphic.setVisible(true);
            logInGraphic.setCursor(Cursor.HAND_CURSOR);

            logInGraphic.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    LogIn_Form lgf = new LogIn_Form();
                    lgf.setVisible(true);
                    lgf.pack();
                    lgf.setLocationRelativeTo(null);
                    lgf.setDefaultCloseOperation(EXIT_ON_CLOSE);
                }
            }
            );
            this.dispose();
        }
    }//GEN-LAST:event_lbl_imageUpMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(Home.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        if (tbl_Address.getSelectedRow() != -1) {
            // remove selected row from the model
            Connection con = MysqlConnect.getConnection();
            PreparedStatement ps;
            ArrayList<String> user = new ArrayList<>();
            ResultSet rs;
            try {
                ps = con.prepareStatement("SELECT `username` FROM `address`");
                rs = ps.executeQuery();
                while (rs.next()) {
                    user.add(rs.getString(1));
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Something went Wrong");
            }
            for (String users : user) {
                try {
                    ps = con.prepareStatement("SELECT `address1`,`address2`,`address3` FROM `address` WHERE `username`=?");
                    ps.setString(1, users);
                    rs = ps.executeQuery();
                    if (rs.next()) {
                        String a1 = rs.getString(1);
                        String a2 = rs.getString(2);
                        String a3 = rs.getString(3);
                        if (tbl_Address.getValueAt(tbl_Address.getSelectedRow(), 1).equals(a1)) {
                            String query = "UPDATE `address`  SET address1=NULL , group1=NULL WHERE username='" + users + "'";
                            DtbsHelper.edıtInfo(7, query);
                        } else if (tbl_Address.getValueAt(tbl_Address.getSelectedRow(), 1).equals(a2)) {
                            String query = "UPDATE `address`  SET address2=NULL, group2=NULL where username='" + users + "'";
                            DtbsHelper.edıtInfo(7, query);
                        } else if (tbl_Address.getValueAt(tbl_Address.getSelectedRow(), 1).equals(a3)) {
                            String query = "UPDATE `address`  SET address3=NULL , group3=NULL where username='" + users + "'";
                            DtbsHelper.edıtInfo(7, query);

                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            DefaultTableModel model = (DefaultTableModel) tbl_Address.getModel();
            model.removeRow(tbl_Address.getSelectedRow());
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void rbtn_blackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_blackActionPerformed
        if (rbtn_black.isSelected()) {
            jPanel1.setBackground(new Color(153, 153, 153));
            jLabel1.setForeground(new Color(18, 30, 49));
            lbl_b4.setIcon(new ImageIcon(getClass().getResource("/İcon/Darktheme.jpg")));
            lbl_b5.setIcon(new ImageIcon(getClass().getResource("/İcon/Darktheme.jpg")));
            lbl_b6.setIcon(new ImageIcon(getClass().getResource("/İcon/Darktheme.jpg")));
            lbl_b7.setIcon(new ImageIcon(getClass().getResource("/İcon/Darktheme.jpg")));
            lbl_welcome.setForeground(new Color(250, 250, 250));
            jLabel5.setForeground(new Color(250, 250, 250));
            lbl_NewPassword.setForeground(new Color(250, 250, 250));
            jLabel7.setForeground(new Color(250, 250, 250));
            jLabel8.setForeground(new Color(250, 250, 250));
            rbtn_male.setForeground(new Color(250, 250, 250));
            rbtn_female.setForeground(new Color(250, 250, 250));

        } else {
            jPanel1.setBackground(new Color(250, 250, 250));
            jLabel1.setForeground(new Color(200, 35, 35));
            lbl_b4.setIcon(new ImageIcon(getClass().getResource("/İcon/backgroundHome.jpg")));
            lbl_b5.setIcon(new ImageIcon(getClass().getResource("/İcon/backgroundHome.jpg")));
            lbl_b6.setIcon(new ImageIcon(getClass().getResource("/İcon/backgroundHome.jpg")));
            lbl_b7.setIcon(new ImageIcon(getClass().getResource("/İcon/backgroundHome.jpg")));
            lbl_welcome.setForeground(new Color(0, 0, 0));
            jLabel5.setForeground(new Color(0, 0, 0));
            lbl_NewPassword.setForeground(new Color(0, 0, 0));
            jLabel7.setForeground(new Color(0, 0, 0));
            jLabel8.setForeground(new Color(0, 0, 0));
            rbtn_male.setForeground(new Color(0, 0, 0));
            rbtn_female.setForeground(new Color(0, 0, 0));

        }
    }//GEN-LAST:event_rbtn_blackActionPerformed
    int xx, xy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        setOpacity((float) 0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:,
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        // TODO add your handling code here:
        setOpacity((float) 1.0);
    }//GEN-LAST:event_jPanel1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_get;
    private javax.swing.JButton btn_image;
    private javax.swing.JButton btn_register;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_NewPassword;
    private javax.swing.JLabel lbl_b4;
    private javax.swing.JLabel lbl_b5;
    private javax.swing.JLabel lbl_b6;
    private javax.swing.JLabel lbl_b7;
    private javax.swing.JLabel lbl_image;
    public javax.swing.JLabel lbl_imageUp;
    private javax.swing.JLabel lbl_picture;
    public javax.swing.JLabel lbl_usernameUp;
    public javax.swing.JLabel lbl_welcome;
    private javax.swing.JPanel pnl_home;
    private javax.swing.JRadioButton rbtn_black;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    public javax.swing.JTable tbl_Address;
    public javax.swing.JTable tbl_feedbacks;
    private javax.swing.JTextField txt_NPassword;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
