/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Class.DtbsHelper;
import Class.LogInGraphic;
import Class.MysqlConnect;
import java.awt.Cursor;
import java.awt.Font;

import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yunus
 */
public class LogIn_Form extends javax.swing.JFrame {

    /**
     * Creates new form LogIn_Form
     */
    public LogIn_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chbx_showPass = new javax.swing.JCheckBox();
        chbx_logınAs = new javax.swing.JComboBox<>();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_cancel = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_sıgnUp = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(450, 450));
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        chbx_showPass.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        chbx_showPass.setForeground(new java.awt.Color(0, 0, 0));
        chbx_showPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbx_showPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chbx_showPassMouseClicked(evt);
            }
        });
        jPanel1.add(chbx_showPass);
        chbx_showPass.setBounds(350, 260, 30, 30);

        chbx_logınAs.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        chbx_logınAs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        jPanel1.add(chbx_logınAs);
        chbx_logınAs.setBounds(170, 300, 170, 27);

        txt_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_username);
        txt_username.setBounds(170, 210, 170, 30);

        txt_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_password);
        txt_password.setBounds(170, 260, 170, 30);

        btn_cancel.setBackground(new java.awt.Color(255, 51, 51));
        btn_cancel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/iconfinder_cancel_326554 (1).png"))); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelMouseClicked(evt);
            }
        });
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancel);
        btn_cancel.setBounds(30, 350, 150, 40);

        btn_register.setBackground(new java.awt.Color(255, 255, 153));
        btn_register.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btn_register.setForeground(new java.awt.Color(0, 0, 0));
        btn_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/iconfinder_login_account_enter_door_3005767.png"))); // NOI18N
        btn_register.setText("Log In");
        btn_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        jPanel1.add(btn_register);
        btn_register.setBounds(220, 350, 150, 40);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/Show.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(380, 260, 30, 30);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/Password.png"))); // NOI18N
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 250, 40, 40);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/username.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 200, 40, 40);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Login As :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 290, 100, 40);

        lbl_sıgnUp.setBackground(new java.awt.Color(255, 255, 255));
        lbl_sıgnUp.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lbl_sıgnUp.setForeground(new java.awt.Color(0, 0, 0));
        lbl_sıgnUp.setText("Don't have a account?  Sıgn Up");
        lbl_sıgnUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_sıgnUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_sıgnUpMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_sıgnUp);
        lbl_sıgnUp.setBounds(160, 410, 260, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Password:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 250, 100, 40);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Username:");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 200, 100, 40);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/iconfinder_people_2639885.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 40, 140, 120);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("LOG IN");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 150, 170, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("X");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("--");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 370, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 450, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/background.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(450, 450));
        jLabel1.setMinimumSize(new java.awt.Dimension(450, 450));
        jLabel1.setPreferredSize(new java.awt.Dimension(450, 450));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 450);

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(450, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chbx_showPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chbx_showPassMouseClicked
        if (chbx_showPass.isSelected()) {
            txt_password.setEchoChar((char) 0);
        } else {
            txt_password.setEchoChar('*');
        }

    }//GEN-LAST:event_chbx_showPassMouseClicked

    private void btn_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseClicked
        this.dispose();
//       System.exit(0);
    }//GEN-LAST:event_btn_cancelMouseClicked

    private void lbl_sıgnUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sıgnUpMouseClicked
        SıgnUp_Form suf = new SıgnUp_Form();
        suf.setVisible(true);
        suf.pack();
        suf.setLocationRelativeTo(null);
        suf.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lbl_sıgnUpMouseClicked

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        if (chbx_logınAs.getSelectedIndex() == 0) {
            Connection con = MysqlConnect.getConnection();
            PreparedStatement ps;
            ResultSet rs;
            try {
                ps = con.prepareStatement("SELECT `username`, `pass`, `pic` FROM `users` WHERE `username`=? AND `pass`=?");
                ps.setString(1, txt_username.getText());
                ps.setString(2, String.valueOf(String.valueOf(txt_password.getPassword())));
                rs = ps.executeQuery();
                if (rs.next()) {
                    //i  used graphics at here for successfully login
                    LogInGraphic logInGraphic = new LogInGraphic();
                    logInGraphic.setLocationRelativeTo(null);
                    logInGraphic.setVisible(true);
                    logInGraphic.setCursor(Cursor.HAND_CURSOR);
                    logInGraphic.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            Home home = new Home();
                            home.setVisible(true);
                            home.pack();
                            home.setLocationRelativeTo(null);
                            home.setDefaultCloseOperation(EXIT_ON_CLOSE);
                            try {
                                home.lbl_picture.setIcon(new DtbsHelper().rezisePic(null, rs.getBytes(3), home.lbl_picture));
                            } catch (SQLException ex) {
                                Logger.getLogger(LogIn_Form.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            home.lbl_usernameUp.setFont(new Font("Algerian", Font.BOLD, 18));
                            try {
                                home.lbl_usernameUp.setText(rs.getString(1));
                            } catch (SQLException ex) {
                                Logger.getLogger(LogIn_Form.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            home.lbl_welcome.setFont(new Font("Algerian", Font.BOLD, 24));
                            try {
                                home.lbl_welcome.setText("WELCOME BACK:" + rs.getString(1));
                            } catch (SQLException ex) {
                                Logger.getLogger(LogIn_Form.class.getName()).log(Level.SEVERE, null, ex);
                            }

                            new DtbsHelper().getTable((DefaultTableModel) home.tbl_Address.getModel(), txt_username.getText(), 0);
                        }
                    }
                    );
                    this.setVisible(false);

                } else {
                    JOptionPane.showMessageDialog(null, "Login Error");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Something went Wrong");
            }
        } else {
            Connection con = MysqlConnect.getConnection();
            PreparedStatement ps;
            ResultSet rs;
            try {
                ps = con.prepareStatement("SELECT `username`, `pass`, `pic` FROM `admın` WHERE `username`=? AND `pass`=?");
                ps.setString(1, txt_username.getText());
                ps.setString(2, String.valueOf(String.valueOf(txt_password.getPassword())));
                rs = ps.executeQuery();
                if (rs.next()) {
                    //i  used graphics at here for successfully login
                    LogInGraphic logInGraphic = new LogInGraphic();
                    logInGraphic.setLocationRelativeTo(null);
                    logInGraphic.setVisible(true);
                    logInGraphic.setCursor(Cursor.HAND_CURSOR);
                    logInGraphic.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            AdminHome home = new AdminHome();
                            home.setVisible(true);
                            home.pack();
                            home.setLocationRelativeTo(null);
                            home.setDefaultCloseOperation(EXIT_ON_CLOSE);
                            try {
                                home.lbl_imageUp.setIcon(new DtbsHelper().rezisePic(null, rs.getBytes(3), home.lbl_imageUp));
                            } catch (SQLException ex) {
                                Logger.getLogger(LogIn_Form.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            home.lbl_usernameUp.setFont(new Font("Algerian", Font.BOLD, 18));
                            try {
                                home.lbl_usernameUp.setText(rs.getString(1));
                            } catch (SQLException ex) {
                                Logger.getLogger(LogIn_Form.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            home.lbl_welcome.setFont(new Font("Algerian", Font.BOLD, 24));
                            try {
                                home.lbl_welcome.setText("WELCOME BACK:" + rs.getString(1));
                            } catch (SQLException ex) {
                                Logger.getLogger(LogIn_Form.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                    );
                    this.setVisible(false);

                } else {
                    JOptionPane.showMessageDialog(null, "Login Error");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Something went Wrong");
            }

        }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.setState(Home.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked
    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        setOpacity((float) 0.5);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        // TODO add your handling code here:
        setOpacity((float) 1.0);

    }//GEN-LAST:event_jPanel2MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_register;
    private javax.swing.JComboBox<String> chbx_logınAs;
    private javax.swing.JCheckBox chbx_showPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_sıgnUp;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
