/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.sql.*;
import java.sql.Connection;
import Class.DtbsHelper;
import Class.MysqlConnect;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author yunus
 */
public class SıgnUp_Form extends javax.swing.JFrame {

    /**
     * Creates new form SıgnUp_Form
     */
    String imagePth = null;

    public SıgnUp_Form() {
        initComponents();
        chbx_termofuse.setEnabled(false);
        lbl_warning1.setVisible(false);
//        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_signUp = new javax.swing.JPanel();
        chbx_termofuse = new javax.swing.JCheckBox();
        txt_repassword = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        btn_image = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        lbl_warning1 = new javax.swing.JLabel();
        lbl_termofUse = new javax.swing.JLabel();
        lbl_image = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(450, 600));
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnl_signUp.setBackground(new java.awt.Color(255, 255, 255));
        pnl_signUp.setLayout(null);

        chbx_termofuse.setForeground(new java.awt.Color(0, 0, 0));
        chbx_termofuse.setText("I accept ");
        pnl_signUp.add(chbx_termofuse);
        chbx_termofuse.setBounds(230, 460, 80, 20);
        pnl_signUp.add(txt_repassword);
        txt_repassword.setBounds(190, 410, 170, 30);

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        pnl_signUp.add(txt_password);
        txt_password.setBounds(190, 370, 170, 30);

        txt_surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_surnameActionPerformed(evt);
            }
        });
        pnl_signUp.add(txt_surname);
        txt_surname.setBounds(190, 290, 170, 30);
        pnl_signUp.add(txt_username);
        txt_username.setBounds(190, 330, 170, 30);

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        pnl_signUp.add(txt_name);
        txt_name.setBounds(190, 250, 170, 30);

        btn_image.setBackground(new java.awt.Color(255, 248, 220));
        btn_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/photo.png"))); // NOI18N
        btn_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imageActionPerformed(evt);
            }
        });
        pnl_signUp.add(btn_image);
        btn_image.setBounds(300, 160, 40, 30);

        btn_reset.setBackground(new java.awt.Color(255, 51, 51));
        btn_reset.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(0, 0, 0));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/clear.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });
        pnl_signUp.add(btn_reset);
        btn_reset.setBounds(50, 490, 150, 40);

        btn_register.setBackground(new java.awt.Color(255, 255, 153));
        btn_register.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btn_register.setForeground(new java.awt.Color(0, 0, 0));
        btn_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/verify.png"))); // NOI18N
        btn_register.setText("Register");
        btn_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        pnl_signUp.add(btn_register);
        btn_register.setBounds(220, 490, 150, 40);

        lbl_warning1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lbl_warning1.setForeground(new java.awt.Color(255, 0, 0));
        lbl_warning1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_warning1.setText("Warnings");
        pnl_signUp.add(lbl_warning1);
        lbl_warning1.setBounds(20, 550, 420, 18);

        lbl_termofUse.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_termofUse.setForeground(new java.awt.Color(0, 0, 0));
        lbl_termofUse.setText("Term of Use");
        lbl_termofUse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_termofUseMouseClicked(evt);
            }
        });
        pnl_signUp.add(lbl_termofUse);
        lbl_termofUse.setBounds(300, 460, 90, 20);
        pnl_signUp.add(lbl_image);
        lbl_image.setBounds(150, 50, 150, 140);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Already have account?  Log In");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        pnl_signUp.add(jLabel9);
        jLabel9.setBounds(170, 570, 240, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Retype Pass:");
        pnl_signUp.add(jLabel8);
        jLabel8.setBounds(50, 410, 100, 40);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Password:");
        pnl_signUp.add(jLabel7);
        jLabel7.setBounds(50, 370, 100, 40);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Username:");
        pnl_signUp.add(jLabel5);
        jLabel5.setBounds(50, 330, 100, 40);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("First Name:");
        pnl_signUp.add(jLabel6);
        jLabel6.setBounds(50, 250, 100, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Last Name:");
        pnl_signUp.add(jLabel4);
        jLabel4.setBounds(50, 290, 100, 40);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SIGN UP");
        pnl_signUp.add(jLabel2);
        jLabel2.setBounds(170, 170, 170, 80);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("X");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("--");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 370, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_signUp.add(jPanel2);
        jPanel2.setBounds(0, 0, 450, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İmages/background.jpg"))); // NOI18N
        pnl_signUp.add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 600);

        getContentPane().add(pnl_signUp);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_surnameActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        LogIn_Form lif = new LogIn_Form();
        lif.setVisible(true);
        lif.pack();
        lif.setLocationRelativeTo(null);
        lif.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
        txt_name.setText("");
        txt_surname.setText("");
        txt_username.setText("");
        txt_password.setText("");
        txt_repassword.setText("");
        if (chbx_termofuse.isSelected()) {
            chbx_termofuse.setSelected(false);
        }
        //lbl_image.setIcon(null);
    }//GEN-LAST:event_btn_resetMouseClicked

    private void lbl_termofUseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_termofUseMouseClicked
        // Show Term OF Use Information;
        int termofUse = JOptionPane.showConfirmDialog(this, "This is for your Personel data.Do you accept sharing your Info?", "WARNING", JOptionPane.YES_NO_OPTION);
        if (termofUse == JOptionPane.YES_OPTION) {
            chbx_termofuse.setEnabled(true);
            chbx_termofuse.setSelected(true);
        } else {
            chbx_termofuse.setSelected(false);
        }
    }//GEN-LAST:event_lbl_termofUseMouseClicked

    private void btn_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imageActionPerformed
        JFileChooser filec = new JFileChooser();
        filec.setCurrentDirectory(new File(System.getProperty("user.home")));
        //file extension
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("*.Images", "jpg", "png", "gif");
        filec.addChoosableFileFilter(fileFilter);
        int fileState = filec.showSaveDialog(null);
        if (fileState == JFileChooser.APPROVE_OPTION) {
            File selectedFile = filec.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            imagePth = path;
            //show the image in the Jlabel
            lbl_image.setIcon(DtbsHelper.rezisePic(path, null, lbl_image));
        }//if the user click cancel 
        else if (fileState == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "No image selected");
        }
        {
        }
    }//GEN-LAST:event_btn_imageActionPerformed
    public boolean verifyData() {
        // regex
        Matcher mtch;
        if (txt_name.getText().isEmpty()) {
            lbl_warning1.setText("Name must not be empty.Please fill that!");
            lbl_warning1.setVisible(true);
            return false;
        } else {
            mtch = Pattern.compile("^[a-zA-Z]{3,}$").matcher(txt_name.getText());
            if (!mtch.find()) {
                lbl_warning1.setText("Name must be at least 3 character and No Number");
                lbl_warning1.setVisible(true);
                return false;
            } else {
                lbl_warning1.setVisible(false);

            }
        }
        if (txt_surname.getText().isEmpty()) {
            lbl_warning1.setText("SurName must not be empty.Please fill that!");
            lbl_warning1.setVisible(true);
            return false;
        } else {
            mtch = Pattern.compile("^[a-zA-Z]{2,}$").matcher(txt_surname.getText());
            if (!mtch.find()) {
                lbl_warning1.setText("SurName must be at least 2 character and No Number");
                lbl_warning1.setVisible(true);
                return false;
            } else {
                lbl_warning1.setVisible(false);

            }
        }
        if (txt_username.getText().isEmpty()) {
            lbl_warning1.setText("UserName must not be empty.Please fill that!");
            lbl_warning1.setVisible(true);
            return false;
        } else {
            mtch = Pattern.compile("^[a-zA-Z0-9]([._-](?![._-])|[a-zA-Z0-9]){3,13}[a-zA-Z0-9]$").matcher(txt_username.getText());
            if (!mtch.find()) {
                lbl_warning1.setText("UserName cannot be like that");
                lbl_warning1.setVisible(true);
                return false;
            } else {
                lbl_warning1.setVisible(false);

            }
        }
        if (txt_password.getText().isEmpty() || txt_repassword.getText().isEmpty()) {
            lbl_warning1.setText("Password must not be empty.Please fill that!");
            lbl_warning1.setVisible(true);
            return false;
        } else {
            mtch = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$").matcher(txt_password.getText());
            if (!mtch.find()) {
                /* At least one upper case English letter, (?=.*?[A-Z])
                At least one lower case English letter, (?=.*?[a-z])
                At least one digit, (?=.*?[0-9])
                At least one special character, (?=.*?[#?!@$%^&*-])
                Minimum eight in length .{8,} (with the anchors)*/
                lbl_warning1.setText("This area must be like \"yunus_Smr1?\"");
                lbl_warning1.setVisible(true);
                return false;
            } else {
                if (!txt_password.getText().equals(txt_repassword.getText())) {
                    lbl_warning1.setText("Passwords are not equal");
                    lbl_warning1.setVisible(true);
                } else {
                    lbl_warning1.setVisible(false);
                }

            }
        }
        if (imagePth == null) {
            JOptionPane.showMessageDialog(null, "Please upload a profil image");
            return false;
        }
        if (!chbx_termofuse.isSelected()) {
            lbl_warning1.setText("Please accept Term Of Use");
            lbl_warning1.setVisible(true);
            return false;
        }

        return true;
    }


    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed

        if (verifyData()) {
            Connection con = MysqlConnect.getConnection();
            PreparedStatement ps;
            try {
                ps = con.prepareStatement("INSERT INTO `users`(`fname`, `lname`, `username`, `pass`, `pic`,`phone`, `email`, `gender`) VALUES (?,?,?,?,?,?,?,?)");
                ps.setString(1, txt_name.getText());
                ps.setString(2, txt_surname.getText());
                ps.setString(3, txt_username.getText());
                ps.setString(4, String.valueOf(txt_password.getText()));
                InputStream img = new FileInputStream(new File(imagePth));
                ps.setBlob(5, img);
                ps.setString(6, "");
                ps.setString(7, "");
                ps.setString(8, "");

                if (new DtbsHelper().isUsernameExist(txt_username.getText(), "users")) {
                    JOptionPane.showMessageDialog(null, "Username Already Exist");
                } else {
                    if (ps.executeUpdate() != 0) {

                        JOptionPane.showMessageDialog(null, "Account created");
                    } else {
                        // i can use grafics at here 

                        JOptionPane.showMessageDialog(null, "Something went wrong:(");
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Something went Wrong");
            }

        } else {
        }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.setState(Home.ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked
    int xx, xy;
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        setOpacity((float) 0.5);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        // TODO add your handling code here:
        setOpacity((float) 1.0);
    }//GEN-LAST:event_jPanel2MouseReleased

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SıgnUp_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SıgnUp_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SıgnUp_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SıgnUp_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SıgnUp_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_image;
    private javax.swing.JButton btn_register;
    private javax.swing.JButton btn_reset;
    private javax.swing.JCheckBox chbx_termofuse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_termofUse;
    private javax.swing.JLabel lbl_warning1;
    private javax.swing.JPanel pnl_signUp;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_repassword;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
